### ISSUE TITLE
remove the /image/v2 prefix

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#6]
I have a perspective in mind, I'm not sure if it's reasonable or doable (or in contradiction with the iif spec), but basically it's the following: *having permanent identifiers for images*. This implies that an image is not dependent of the iiif version, and we need to have a iiif-server-independant way to refer to them, and thus we need to completely control the URL of the images in the image server. Hence the request. It's quite obvious for annotations: when someone annotates an image provided in iiif v2, we don't want their annotation not to work anymore when we'll move to iiifv3.

**Comment by MarcAgate** [comment]
As far as I can tell, according to https://iiif.io/api/image/2.1/#uri-syntax, image/v2 corresponds to the {prefix} part of the url which is said to be optional. Therefore, we can get rid of it without contradicting iiif specs.
In hymir implementation, image/v2 is set in the IIIFImageApiController as the common root of the services. We can certainly change that part in a custom IIIFImageApiController (I am already using such a custom version of the controller in order to avoid some CORS headers settings that do not match our needs)

**Comment by eroux** [comment]
Right, that's a reasonable short-term solution, but in the long term it would be best if hymir allows it, for maintenance reasons

**Comment by eroux** [comment]
@MarcAgate do you think you could implement that? I'd like to write a small doc on our IIIF URLs for partners (someone made such a request), but it would be best if it was using the final URL scheme...

**Comment by MarcAgate** [comment]
Yes, that's feasible. I am going to try that today. Do you just want to remove /image/v2 or do you want to replace it with something else ? (i.e http://iiif.bdrc.io/image/v2/bdr:V29199_I5166::51660001.tif/info.json could become http://iiif.bdrc.io/bdr:V29199_I5166::51660001.tif/info.json or http://iiif.bdrc.io/somethingelse/bdr:V29199_I5166::51660001.tif/info.json)
