### ISSUE TITLE
issue with number of pages in PDF

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-iiif-server#81]
see original query:

https://github.com/buda-base/public-digital-library/issues/496

possibly linked to https://github.com/buda-base/buda-iiif-server/issues/53

**Comment by berger-n** [comment]
`volnum` value does not seem to match volume order: http://iiif.bdrc.io/download/pdf/wi:bdr:W3PD1100::bdr:I3PD1100

![image](https://user-images.githubusercontent.com/33383857/120687359-3b165f00-c4a2-11eb-9c77-6ec417cd6d68.png)

**Comment by eroux** [comment]
hmm, very odd... thanks for noticing that!

**Comment by MarcAgate** [comment]
Very odd indeed...
What data do we use inside the viewer for this view ?  https://library.bdrc.io/show/bdr:W3PD1100?s=%2Fshow%2Fbdr%3AMW3PD1100%3Ftabs%3Dbdr%3AW3PD1100#open-viewer

I suppose we are making the same request, don't we ?

**Comment by eroux** [comment]
ok that should be fixed... @MarcAgate can you test? Thanks for the report BTW!

**Comment by berger-n** [comment]
thanks @eroux! looks better to me:

![image](https://user-images.githubusercontent.com/33383857/120769860-d4cf2200-c51d-11eb-99f8-31a779528cf0.png)

volume ordering now starts at 1 instead of 0, is it on purpose? 
if so I'll need to update library where first volume now has number 2:

![image](https://user-images.githubusercontent.com/33383857/120769944-e9131f00-c51d-11eb-862e-2e8b501906eb.png)

**Comment by eroux** [comment]
Yes, it should have always been the case, the previous state was really buggy

**Comment by berger-n** [comment]
ok! done: https://library.bdrc.io/show/bdr:W3PD1100

![image](https://user-images.githubusercontent.com/33383857/120779547-7313b580-c527-11eb-9fa4-fb9902757641.png)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by MarcAgate** [comment]
I had planned to fix that this WE, you've been faster! That's fine! I tested it and it works nicely now. I let you guys close the issue.
